// GSD DB Writer — Markdown generators + DB-first write helpers
//
// The missing DB→markdown direction. S03 established markdown→DB (md-importer.ts).
// This module generates DECISIONS.md and REQUIREMENTS.md from DB state,
// computes next decision IDs, and provides write helpers that upsert to DB
// then regenerate the corresponding markdown file.
//
// Critical invariant: generated markdown must round-trip through
// parseDecisionsTable() and parseRequirementsSections() with field fidelity.

import { isAbsolute, join, relative, resolve } from 'node:path';
import { readFileSync, existsSync, statSync } from 'node:fs';
import type { Decision, Requirement } from './types.js';
import { resolveGsdRootFile } from './paths.js';
import { saveFile } from './files.js';
import { GSDError, GSD_STALE_STATE, GSD_IO_ERROR } from './errors.js';
import { logWarning, logError } from './workflow-logger.js';
import { invalidateStateCache } from './state.js';
import { clearPathCache } from './paths.js';
import { clearParseCache } from './files.js';
import type { MilestoneScope, GsdWorkspace } from './workspace.js';
import { createWorkspace, scopeMilestone } from './workspace.js';

// ─── Freeform Detection ───────────────────────────────────────────────────

/**
 * Detect whether a DECISIONS.md file is in canonical table format
 * (generated by generateDecisionsMd).
 *
 * Returns true only if the file starts with the canonical header
 * ("# Decisions Register") that generateDecisionsMd produces.
 * Files with freeform content — even if they contain an appended
 * decisions table section — return false so the freeform content
 * is preserved.
 */
export function isDecisionsTableFormat(content: string): boolean {
  // The canonical format always starts with "# Decisions Register"
  const firstLine = content.split('\n')[0]?.trim() ?? '';
  if (firstLine !== '# Decisions Register') return false;

  // Additionally verify the file has the canonical table header
  return content.includes('| # | When | Scope | Decision | Choice | Rationale | Revisable?');
}

/**
 * Generate a minimal decisions table section (header + rows) for appending
 * to a freeform DECISIONS.md file.
 */
function generateDecisionsAppendBlock(decisions: Decision[]): string {
  const lines: string[] = [];
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Decisions Table');
  lines.push('');
  lines.push('| # | When | Scope | Decision | Choice | Rationale | Revisable? | Made By |');
  lines.push('|---|------|-------|----------|--------|-----------|------------|---------|');

  for (const d of decisions) {
    const cells = [
      d.id,
      d.when_context,
      d.scope,
      d.decision,
      d.choice,
      d.rationale,
      d.revisable,
      d.made_by ?? 'agent',
    ].map(cell => (cell ?? '').replace(/\|/g, '\\|'));
    lines.push(`| ${cells.join(' | ')} |`);
  }

  return lines.join('\n') + '\n';
}

// ─── Markdown Generators ──────────────────────────────────────────────────

/**
 * Generate full DECISIONS.md content from an array of Decision objects.
 * Produces the canonical format: H1 header, HTML comment block, table header,
 * separator, and one data row per decision.
 *
 * Column order: #, When, Scope, Decision, Choice, Rationale, Revisable?
 */
export function generateDecisionsMd(decisions: Decision[]): string {
  const lines: string[] = [];

  lines.push('# Decisions Register');
  lines.push('');
  lines.push('<!-- Append-only. Never edit or remove existing rows.');
  lines.push('     To reverse a decision, add a new row that supersedes it.');
  lines.push('     Read this file at the start of any planning or research phase. -->');
  lines.push('');
  lines.push('| # | When | Scope | Decision | Choice | Rationale | Revisable? | Made By |');
  lines.push('|---|------|-------|----------|--------|-----------|------------|---------|');

  for (const d of decisions) {
    // Escape pipe characters within cell values to preserve table structure
    const cells = [
      d.id,
      d.when_context,
      d.scope,
      d.decision,
      d.choice,
      d.rationale,
      d.revisable,
      d.made_by ?? 'agent',
    ].map(cell => (cell ?? '').replace(/\|/g, '\\|'));

    lines.push(`| ${cells.join(' | ')} |`);
  }

  return lines.join('\n') + '\n';
}

// ─── Requirements Markdown Generator ──────────────────────────────────────

/** Status values that map to specific sections, in display order. */
const STATUS_SECTION_MAP: Array<{ status: string; heading: string }> = [
  { status: 'active', heading: 'Active' },
  { status: 'validated', heading: 'Validated' },
  { status: 'deferred', heading: 'Deferred' },
  { status: 'out-of-scope', heading: 'Out of Scope' },
];

/**
 * Generate full REQUIREMENTS.md content from an array of Requirement objects.
 * Groups requirements by status into sections (## Active, ## Validated, etc.),
 * each containing ### RXXX — Description headings with bullet fields. Empty
 * status sections are emitted too because the deep-mode validator treats their
 * presence as part of the canonical contract.
 */
export function generateRequirementsMd(requirements: Requirement[]): string {
  const lines: string[] = [];

  lines.push('# Requirements');
  lines.push('');
  lines.push('This file is the explicit capability and coverage contract for the project.');
  lines.push('');

  // Group by status
  const byStatus = new Map<string, Requirement[]>();
  for (const r of requirements) {
    const status = (r.status || 'active').toLowerCase();
    if (!byStatus.has(status)) byStatus.set(status, []);
    byStatus.get(status)!.push(r);
  }

  // Emit sections in canonical order
  for (const { status, heading } of STATUS_SECTION_MAP) {
    const reqs = byStatus.get(status);
    lines.push(`## ${heading}`);
    lines.push('');

    for (const r of reqs ?? []) {
      lines.push(`### ${r.id} — ${r.description || 'Untitled'}`);

      // Emit bullet fields — only those with content
      if (r.class) lines.push(`- Class: ${r.class}`);
      if (r.status) lines.push(`- Status: ${r.status}`);
      if (r.description) lines.push(`- Description: ${r.description}`);
      if (r.why) lines.push(`- Why it matters: ${r.why}`);
      if (r.source) lines.push(`- Source: ${r.source}`);
      if (r.primary_owner) lines.push(`- Primary owning slice: ${r.primary_owner}`);
      if (r.supporting_slices) lines.push(`- Supporting slices: ${r.supporting_slices}`);
      if (r.validation) lines.push(`- Validation: ${r.validation}`);
      if (r.notes) lines.push(`- Notes: ${r.notes}`);
      lines.push('');
    }
  }

  // Traceability table
  lines.push('## Traceability');
  lines.push('');
  lines.push('| ID | Class | Status | Primary owner | Supporting | Proof |');
  lines.push('|---|---|---|---|---|---|');

  for (const r of requirements) {
    const proof = r.validation || 'unmapped';
    lines.push(
      `| ${r.id} | ${r.class || ''} | ${r.status || ''} | ${r.primary_owner || 'none'} | ${r.supporting_slices || 'none'} | ${proof} |`,
    );
  }

  lines.push('');

  // Coverage Summary
  const activeCount = byStatus.get('active')?.length ?? 0;
  const validatedReqs = byStatus.get('validated') ?? [];
  const validatedIds = validatedReqs.map(r => r.id).join(', ');

  lines.push('## Coverage Summary');
  lines.push('');
  lines.push(`- Active requirements: ${activeCount}`);
  lines.push(`- Mapped to slices: ${activeCount}`);
  lines.push(`- Validated: ${validatedReqs.length}${validatedIds ? ` (${validatedIds})` : ''}`);
  lines.push(`- Unmapped active requirements: 0`);

  return lines.join('\n') + '\n';
}

function isRootCanonicalArtifact(opts: SaveArtifactOpts): boolean {
  if (opts.milestone_id || opts.slice_id || opts.task_id) return false;
  return (
    opts.artifact_type === 'PROJECT' ||
    opts.artifact_type === 'REQUIREMENTS'
  );
}

// ─── Next Decision ID ─────────────────────────────────────────────────────

/**
 * Compute the next decision ID from the current DB state.
 * Queries MAX(CAST(SUBSTR(id, 2) AS INTEGER)) from decisions table.
 * Returns D001 if no decisions exist. Zero-pads to 3 digits.
 */
export async function nextDecisionId(): Promise<string> {
  try {
    const db = await import('./gsd-db.js');
    const adapter = db._getAdapter();
    if (!adapter) return 'D001';

    const row = adapter
      .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM decisions')
      .get();

    const maxNum = row ? (row['max_num'] as number | null) : null;
    if (maxNum == null || isNaN(maxNum)) return 'D001';

    const next = maxNum + 1;
    return `D${String(next).padStart(3, '0')}`;
  } catch (err) {
    logError('manifest', 'nextDecisionId failed', { fn: 'nextDecisionId', error: String((err as Error).message) });
    return 'D001';
  }
}

/** Synchronous variant for use inside db.transaction(). */
function nextDecisionIdSync(adapter: ReturnType<typeof import('./gsd-db.js')._getAdapter>): string {
  if (!adapter) return 'D001';
  const row = adapter
    .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM decisions')
    .get();
  const maxNum = row ? (row['max_num'] as number | null) : null;
  if (maxNum == null || isNaN(maxNum)) return 'D001';
  const next = maxNum + 1;
  return `D${String(next).padStart(3, '0')}`;
}

// ─── Next Requirement ID ─────────────────────────────────────────────────

/**
 * Compute the next requirement ID from the current DB state.
 * Queries MAX(CAST(SUBSTR(id, 2) AS INTEGER)) from requirements table.
 * Returns R001 if no requirements exist. Zero-pads to 3 digits.
 */
export async function nextRequirementId(): Promise<string> {
  try {
    const db = await import('./gsd-db.js');
    const adapter = db._getAdapter();
    if (!adapter) return 'R001';

    const row = adapter
      .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM requirements')
      .get();

    const maxNum = row ? (row['max_num'] as number | null) : null;
    if (maxNum == null || isNaN(maxNum)) return 'R001';

    const next = maxNum + 1;
    return `R${String(next).padStart(3, '0')}`;
  } catch (err) {
    logError('manifest', 'nextRequirementId failed', { fn: 'nextRequirementId', error: String((err as Error).message) });
    return 'R001';
  }
}

// ─── Save Requirement to DB + Regenerate Markdown ────────────────────────

export interface SaveRequirementFields {
  class: string;
  status?: string;
  description: string;
  why: string;
  source: string;
  primary_owner?: string;
  supporting_slices?: string;
  validation?: string;
  notes?: string;
}

/**
 * Save a new requirement to DB and regenerate REQUIREMENTS.md.
 * Auto-assigns the next ID via nextRequirementId().
 *
 * The ID computation and insert are wrapped in a single transaction
 * to prevent parallel race conditions (same pattern as saveDecisionToDb).
 *
 * Returns the assigned ID.
 */
export async function saveRequirementToDb(
  fields: SaveRequirementFields,
  basePath: string,
): Promise<{ id: string }> {
  try {
    const db = await import('./gsd-db.js');

    // Atomic ID assignment + insert inside a transaction.
    const txResult = db.transaction(() => {
      const adapter = db._getAdapter();
      if (!adapter) throw new GSDError(GSD_STALE_STATE, "gsd-db: No database open");

      const existingRow = adapter
        .prepare(
          `SELECT * FROM requirements
           WHERE LOWER(TRIM(description)) = LOWER(TRIM(:description))
             AND LOWER(COALESCE(status, 'active')) = 'active'
             AND superseded_by IS NULL
           ORDER BY id
           LIMIT 1`,
        )
        .get({ ':description': fields.description });
      const row = adapter
        .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM requirements')
        .get();
      const maxNum = row ? (row['max_num'] as number | null) : null;
      const nextId = existingRow
        ? String(existingRow['id'])
        : (maxNum == null || isNaN(maxNum))
        ? 'R001'
        : `R${String(maxNum + 1).padStart(3, '0')}`;

      const requirement: Requirement = {
        id: nextId,
        class: fields.class || (existingRow?.['class'] as string | undefined) || '',
        status: fields.status ?? (existingRow?.['status'] as string | undefined) ?? 'active',
        description: fields.description,
        why: fields.why,
        source: fields.source,
        primary_owner: fields.primary_owner ?? (existingRow?.['primary_owner'] as string | undefined) ?? '',
        supporting_slices: fields.supporting_slices ?? (existingRow?.['supporting_slices'] as string | undefined) ?? '',
        validation: fields.validation ?? (existingRow?.['validation'] as string | undefined) ?? '',
        notes: fields.notes ?? (existingRow?.['notes'] as string | undefined) ?? '',
        full_content: (existingRow?.['full_content'] as string | undefined) ?? '',
        superseded_by: (existingRow?.['superseded_by'] as string | null | undefined) ?? null,
      };

      db.upsertRequirement(requirement);
      return { id: nextId };
    });
    const { id } = txResult;

    // Fetch all requirements for full file regeneration
    const adapter = db._getAdapter();
    let allRequirements: Requirement[] = [];
    if (adapter) {
      const rows = adapter.prepare('SELECT * FROM requirements ORDER BY id').all();
      allRequirements = rows.map(row => ({
        id: row['id'] as string,
        class: row['class'] as string,
        status: row['status'] as string,
        description: row['description'] as string,
        why: row['why'] as string,
        source: row['source'] as string,
        primary_owner: row['primary_owner'] as string,
        supporting_slices: row['supporting_slices'] as string,
        validation: row['validation'] as string,
        notes: row['notes'] as string,
        full_content: row['full_content'] as string,
        superseded_by: (row['superseded_by'] as string) ?? null,
      }));
    }

    const nonSuperseded = allRequirements.filter(r => r.superseded_by == null);
    const md = generateRequirementsMd(nonSuperseded);
    const filePath = resolveGsdRootFile(basePath, 'REQUIREMENTS');
    try {
      await saveFile(filePath, md);
    } catch (diskErr) {
      logWarning('projection', 'REQUIREMENTS.md projection write failed; DB requirement remains committed', { fn: 'saveRequirementToDb', id, error: String((diskErr as Error).message) });
    }
    invalidateStateCache();
    clearPathCache();
    clearParseCache();

    return { id };
  } catch (err) {
    logError('manifest', 'saveRequirementToDb failed', { fn: 'saveRequirementToDb', error: String((err as Error).message) });
    throw err;
  }
}

// ─── Async Mutex for Decision Saves ───────────────────────────────────────
//
// Serializes the entire saveDecisionToDb operation (ID generation + DB upsert
// + file read + markdown regeneration + file write) so that parallel callers
// cannot interleave and produce a last-writer-wins race on DECISIONS.md.
let _decisionSaveLock: Promise<unknown> = Promise.resolve();

/** Reset the mutex — only for tests. */
export function _resetDecisionSaveLock(): void {
  _decisionSaveLock = Promise.resolve();
}

// ─── Save Decision to DB + Regenerate Markdown ────────────────────────────

export interface SaveDecisionFields {
  scope: string;
  decision: string;
  choice: string;
  rationale: string;
  revisable?: string;
  when_context?: string;
  made_by?: import('./types.js').DecisionMadeBy;
  /** ADR-011 Phase 2: origin of the decision — "discussion" (default), "planning", "escalation". */
  source?: string;
}

type NormalizedSaveDecisionFields = Omit<
  SaveDecisionFields,
  'when_context' | 'revisable' | 'made_by' | 'source'
> & {
  when_context: string;
  revisable: string;
  made_by: NonNullable<SaveDecisionFields['made_by']>;
  source: string;
};

/**
 * Save a new decision to DB and regenerate DECISIONS.md.
 * Auto-assigns the next ID via nextDecisionId().
 *
 * Concurrency: uses an async mutex (promise chain) to serialize the entire
 * operation — ID generation, DB upsert, file read, markdown regeneration,
 * and file write — preventing parallel callers from overwriting each other's
 * output (last-writer-wins race condition).
 *
 * Returns the assigned ID.
 */
export async function saveDecisionToDb(
  fields: SaveDecisionFields,
  basePath: string,
): Promise<{ id: string }> {
  // Serialize via async mutex: each call waits for the previous one to
  // complete before starting, preventing interleaved DB + file writes.
  let release: () => void;
  const prev = _decisionSaveLock;
  _decisionSaveLock = new Promise<void>(r => { release = r; });

  try {
    await prev;
  } catch {
    // Previous call failed — proceed regardless; the lock chain must continue.
  }

  try {
    const db = await import('./gsd-db.js');

    const adapter = db._getAdapter();
    const normalized: NormalizedSaveDecisionFields = {
      ...fields,
      when_context: fields.when_context ?? '',
      revisable: fields.revisable ?? 'Yes',
      made_by: fields.made_by ?? 'agent',
      source: fields.source ?? 'discussion',
    };

    const id = db.transaction(() => {
      const nextId = nextDecisionIdSync(adapter);
      db.upsertDecision({
        id: nextId,
        when_context: normalized.when_context,
        scope: normalized.scope,
        decision: normalized.decision,
        choice: normalized.choice,
        rationale: normalized.rationale,
        revisable: normalized.revisable,
        made_by: normalized.made_by,
        source: normalized.source,
        superseded_by: null,
      });


      return nextId;
    });

    // ADR-013 Stage 2a (PR #5767 → #5755): the dual-write to memories MUST
    // happen before the projection regen below, because the regen now sources
    // from memories. If the dual-write ran after, the just-saved decision
    // would be missing from its own projection.
    // mirrorDecisionToMemory is best-effort and swallows its own errors
    // (see its body) — no need to wrap here. Use the normalized field set
    // so the memory row reflects the same defaults that landed in the
    // decisions table.
    await mirrorDecisionToMemory(id, normalized);

    // Fetch all decisions (including superseded for the full register).
    // ADR-013 Stage 2a: source from the `memories` table. The Phase 5
    // dual-write keeps memories in sync with each decision save; the backfill
    // (memory-backfill.ts) absorbs the historical chain and drift-heals
    // superseded_by on every session start.
    const { getAllDecisionsFromMemories } = await import('./context-store.js');
    let allDecisions: Decision[] = getAllDecisionsFromMemories();
    if (!allDecisions.some(d => d.id === id)) {
      logWarning('projection', 'just-saved decision missing from memories after mirror; injecting fallback for projection', {
        fn: 'saveDecisionToDb',
        decisionId: id,
      });
      const nextSeq = allDecisions.reduce((max, d) => Math.max(max, d.seq ?? 0), 0) + 1;
      const fallback: Decision = {
        seq: nextSeq,
        id,
        when_context: normalized.when_context,
        scope: normalized.scope,
        decision: normalized.decision,
        choice: normalized.choice,
        rationale: normalized.rationale,
        revisable: normalized.revisable,
        made_by: normalized.made_by,
        superseded_by: null,
      };
      allDecisions = [...allDecisions, fallback];
    }

    const filePath = resolveGsdRootFile(basePath, 'DECISIONS');

    // Check if existing DECISIONS.md has freeform (non-table) content.
    // If so, preserve that content and append/update the decisions table
    // at the end instead of overwriting the entire file.
    let existingContent: string | null = null;
    if (existsSync(filePath)) {
      existingContent = readFileSync(filePath, 'utf-8');
    }

    let md: string;
    if (existingContent && !isDecisionsTableFormat(existingContent)) {
      // Freeform content detected — preserve it and append decisions table.
      // Strip any previously appended decisions table section to avoid duplication.
      const marker = '---\n\n## Decisions Table';
      const markerIdx = existingContent.indexOf(marker);
      const freeformPart = markerIdx >= 0
        ? existingContent.substring(0, markerIdx).trimEnd()
        : existingContent.trimEnd();
      md = freeformPart + '\n' + generateDecisionsAppendBlock(allDecisions);
    } else {
      // Table format or no existing file — full regeneration (original behavior)
      md = generateDecisionsMd(allDecisions);
    }

    try {
      await saveFile(filePath, md);
    } catch (diskErr) {
      logWarning('projection', 'DECISIONS.md projection write failed; DB decision remains committed', { fn: 'saveDecisionToDb', id, error: String((diskErr as Error).message) });
    }
    // #2661: When a decision defers a slice, update the slice status in the DB
    // so the dispatcher skips it. Without this, STATE.md and DECISIONS.md are
    // in split-brain: the decision says "deferred" but the state still says
    // "active", causing auto-mode to keep dispatching the deferred work.
    try {
      const sliceRef = extractDeferredSliceRef(fields);
      if (sliceRef) {
        db.updateSliceStatus(sliceRef.milestoneId, sliceRef.sliceId, 'deferred');
      }
    } catch (deferErr) {
      // Non-fatal — log but don't fail the decision save
      logError('manifest', 'failed to update deferred slice status', {
        fn: 'saveDecisionToDb',
        error: String((deferErr as Error).message),
      });
    }

    // Invalidate file-read caches so deriveState() sees the updated markdown.
    // Do NOT clear the artifacts table — we just wrote to it intentionally.
    invalidateStateCache();
    clearPathCache();
    clearParseCache();

    return { id };
  } catch (err) {
    logError('manifest', 'saveDecisionToDb failed', { fn: 'saveDecisionToDb', error: String((err as Error).message) });
    throw err;
  } finally {
    release!();
  }
}

/**
 * ADR-013 dual-write — mirror a freshly-saved decision into the `memories`
 * table so the memory store remains the single source of truth for the
 * DECISIONS.md projection (Stage 2a) and for prompt-inline reads (Stage 1).
 *
 * Best-effort mirror: logs failures without throwing to avoid blocking saves.
 * Caller invokes this AFTER the decisions-table write completes and
 * BEFORE the projection regen — the regen sources from memories and would
 * otherwise miss the just-saved decision.
 */
async function mirrorDecisionToMemory(
  id: string,
  normalizedFields: NormalizedSaveDecisionFields,
): Promise<boolean> {
  try {
    const { createMemory } = await import('./memory-store.js');
    const { synthesizeDecisionMemoryContent } = await import('./memory-backfill.js');
    const content = synthesizeDecisionMemoryContent(normalizedFields);
    if (!content) return false;

    createMemory({
      category: 'architecture',
      content,
      scope: normalizedFields.scope || 'project',
      confidence: 0.85,
      structuredFields: {
        sourceDecisionId: id,
        when_context: normalizedFields.when_context,
        scope: normalizedFields.scope,
        decision: normalizedFields.decision,
        choice: normalizedFields.choice,
        rationale: normalizedFields.rationale,
        made_by: normalizedFields.made_by,
        revisable: normalizedFields.revisable,
        // New decisions are always written as active; md-importer can later
        // set superseded_by on the source decision row, and the backfill's
        // drift auto-heal pass propagates that update to this memory.
        superseded_by: null,
      },
    });
    return true;
  } catch (mirrorErr) {
    logError('manifest', 'memory-store mirror write failed', {
      fn: 'saveDecisionToDb',
      decisionId: id,
      error: String((mirrorErr as Error).message),
    });
    return false;
  }
}

/**
 * Extract a milestone/slice reference from a deferral decision.
 *
 * Detects deferrals by checking:
 *   - scope contains "defer" (e.g., "deferral", "defer")
 *   - choice or decision contains "defer" + an M###/S## pattern
 *
 * Returns { milestoneId, sliceId } if found, null otherwise.
 */
export function extractDeferredSliceRef(
  fields: Pick<SaveDecisionFields, 'scope' | 'decision' | 'choice'>,
): { milestoneId: string; sliceId: string } | null {
  const isDeferral =
    /\bdefer(?:ral|red|ring|s)?\b/i.test(fields.scope) ||
    /\bdefer(?:ral|red|ring|s)?\b/i.test(fields.choice) ||
    /\bdefer(?:ral|red|ring|s)?\b/i.test(fields.decision);

  if (!isDeferral) return null;

  // Look for M###/S## pattern in choice first, then decision
  const slicePattern = /\b(M\d{3,4})\/(S\d{2,3})\b/;
  const choiceMatch = fields.choice.match(slicePattern);
  if (choiceMatch) {
    return { milestoneId: choiceMatch[1], sliceId: choiceMatch[2] };
  }
  const decisionMatch = fields.decision.match(slicePattern);
  if (decisionMatch) {
    return { milestoneId: decisionMatch[1], sliceId: decisionMatch[2] };
  }

  return null;
}

// ─── Update Requirement in DB + Regenerate Markdown ───────────────────────

/**
 * Update a requirement in DB and regenerate REQUIREMENTS.md.
 * Fetches existing requirement, merges updates, upserts, then regenerates.
 */
export async function updateRequirementInDb(
  id: string,
  updates: Partial<Requirement>,
  basePath: string,
): Promise<void> {
  try {
    const db = await import('./gsd-db.js');

    const existing = db.getRequirementById(id);

    const base: Requirement = existing ?? {
      id,
      class: '',
      status: 'active',
      description: '',
      why: '',
      source: '',
      primary_owner: '',
      supporting_slices: '',
      validation: '',
      notes: '',
      full_content: '',
      superseded_by: null,
    };

    // Merge updates into existing (or skeleton)
    const merged: Requirement = {
      ...base,
      ...updates,
      id: base.id, // ID cannot be changed
    };

    db.upsertRequirement(merged);

    // Fetch ALL requirements (including superseded) for full file regeneration
    const adapter = db._getAdapter();
    let allRequirements: Requirement[] = [];
    if (adapter) {
      const rows = adapter.prepare('SELECT * FROM requirements ORDER BY id').all();
      allRequirements = rows.map(row => ({
        id: row['id'] as string,
        class: row['class'] as string,
        status: row['status'] as string,
        description: row['description'] as string,
        why: row['why'] as string,
        source: row['source'] as string,
        primary_owner: row['primary_owner'] as string,
        supporting_slices: row['supporting_slices'] as string,
        validation: row['validation'] as string,
        notes: row['notes'] as string,
        full_content: row['full_content'] as string,
        superseded_by: (row['superseded_by'] as string) ?? null,
      }));
    }

    // Filter to non-superseded for the markdown file
    // (superseded requirements don't appear in section headings)
    const nonSuperseded = allRequirements.filter(r => r.superseded_by == null);

    const md = generateRequirementsMd(nonSuperseded);
    const filePath = resolveGsdRootFile(basePath, 'REQUIREMENTS');
    try {
      await saveFile(filePath, md);
    } catch (diskErr) {
      logWarning('projection', 'REQUIREMENTS.md projection write failed; DB requirement update remains committed', { fn: 'updateRequirementInDb', id, error: String((diskErr as Error).message) });
    }
    // Invalidate file-read caches so deriveState() sees the updated markdown.
    // Do NOT clear the artifacts table — we just wrote to it intentionally.
    invalidateStateCache();
    clearPathCache();
    clearParseCache();
  } catch (err) {
    logError('manifest', 'updateRequirementInDb failed', { fn: 'updateRequirementInDb', error: String((err as Error).message) });
    throw err;
  }
}

// ─── Save Artifact to DB + Disk ───────────────────────────────────────────

export interface SaveArtifactOpts {
  path: string;
  artifact_type: string;
  content: string;
  milestone_id?: string;
  slice_id?: string;
  task_id?: string;
}

/**
 * Save a root-level artifact (no milestone) to DB and write to disk,
 * routing path construction through workspace.contract.projectGsd directly.
 * Use this instead of saveArtifactToDbByScope when milestone_id is absent.
 */
export async function saveArtifactToDbForWorkspace(
  workspace: GsdWorkspace,
  opts: SaveArtifactOpts,
): Promise<void> {
  try {
    const db = await import('./gsd-db.js');

    const gsdDir = workspace.contract.projectGsd;
    const fullPath = resolve(gsdDir, opts.path);

    const rel0 = relative(gsdDir, fullPath);
    if (rel0.startsWith('..') || isAbsolute(rel0)) {
      throw new GSDError(GSD_IO_ERROR, `saveArtifactToDbForWorkspace: path escapes .gsd/ directory: ${opts.path}`);
    }

    let contentToPersist = opts.content;
    if (opts.artifact_type === 'REQUIREMENTS' && opts.path === 'REQUIREMENTS.md') {
      const activeRequirements = db.getActiveRequirements();
      if (activeRequirements.length === 0) {
        throw new GSDError(GSD_STALE_STATE, 'saveArtifactToDbForWorkspace: REQUIREMENTS final save requires active DB-backed requirements');
      }
      contentToPersist = generateRequirementsMd(activeRequirements);
    }

    let skipDiskWrite = false;
    if (!isRootCanonicalArtifact(opts) && existsSync(fullPath)) {
      const existingSize = statSync(fullPath).size;
      const newSize = Buffer.byteLength(contentToPersist, 'utf-8');
      if (existingSize > 0 && newSize < existingSize * 0.5) {
        logWarning('projection', `new content (${newSize}B) is <50% of existing projection (${existingSize}B), preserving disk file while DB remains authoritative`, { fn: 'saveArtifactToDbForWorkspace', path: opts.path });
        skipDiskWrite = true;
      }
    }

    db.insertArtifact({
      path: opts.path,
      artifact_type: opts.artifact_type,
      milestone_id: null,
      slice_id: null,
      task_id: null,
      full_content: contentToPersist,
    });

    if (!skipDiskWrite) {
      try {
        await saveFile(fullPath, contentToPersist);
      } catch (diskErr) {
        logWarning('projection', 'artifact projection write failed; DB artifact remains committed', { fn: 'saveArtifactToDbForWorkspace', path: opts.path, error: String((diskErr as Error).message) });
      }
    }
    invalidateStateCache();
    clearPathCache();
    clearParseCache();
  } catch (err) {
    logError('manifest', 'saveArtifactToDbForWorkspace failed', { fn: 'saveArtifactToDbForWorkspace', error: String((err as Error).message) });
    throw err;
  }
}

/**
 * Save an artifact to DB and write the corresponding markdown file to disk,
 * routing all path construction through the workspace contract.
 *
 * The path is relative to .gsd/ (e.g. "milestones/M001/slices/S06/tasks/T01-SUMMARY.md").
 * The full file path is computed as scope.workspace.contract.projectGsd + '/' + path.
 */
export async function saveArtifactToDbByScope(
  scope: MilestoneScope,
  opts: SaveArtifactOpts,
): Promise<void> {
  // Guard: an empty milestoneId produces malformed paths (milestoneDir = join(gsd, "milestones", "")).
  // Callers that have no milestone should use saveArtifactToDbForWorkspace instead.
  if (!scope.milestoneId) {
    throw new GSDError(GSD_IO_ERROR, `saveArtifactToDbByScope: milestoneId is empty — use saveArtifactToDbForWorkspace for root artifacts`);
  }

  try {
    const db = await import('./gsd-db.js');

    // Use contract.projectGsd as the canonical .gsd directory — never a hand-rolled basePath join.
    const gsdDir = scope.workspace.contract.projectGsd;
    const fullPath = resolve(gsdDir, opts.path);

    // Guard against path traversal before any reads/writes
    const rel1 = relative(gsdDir, fullPath);
    if (rel1.startsWith('..') || isAbsolute(rel1)) {
      throw new GSDError(GSD_IO_ERROR, `saveArtifactToDbByScope: path escapes .gsd/ directory: ${opts.path}`);
    }

    let contentToPersist = opts.content;
    if (opts.artifact_type === 'REQUIREMENTS' && opts.path === 'REQUIREMENTS.md') {
      const activeRequirements = db.getActiveRequirements();
      if (activeRequirements.length === 0) {
        throw new GSDError(GSD_STALE_STATE, 'saveArtifactToDbByScope: REQUIREMENTS final save requires active DB-backed requirements');
      }
      contentToPersist = generateRequirementsMd(activeRequirements);
    }

    // Shrinkage guard: if the projection file already exists and the new
    // content is significantly smaller (<50%), preserve the richer file on
    // disk, but keep the DB row authoritative with the caller-provided content.
    // Root canonical artifacts are exempt (rendered from canonical DB state).
    let skipDiskWrite = false;
    if (!isRootCanonicalArtifact(opts) && existsSync(fullPath)) {
      const existingSize = statSync(fullPath).size;
      const newSize = Buffer.byteLength(contentToPersist, 'utf-8');
      if (existingSize > 0 && newSize < existingSize * 0.5) {
        logWarning('projection', `new content (${newSize}B) is <50% of existing projection (${existingSize}B), preserving disk file while DB remains authoritative`, { fn: 'saveArtifactToDbByScope', path: opts.path });
        skipDiskWrite = true;
      }
    }

    db.insertArtifact({
      path: opts.path,
      artifact_type: opts.artifact_type,
      milestone_id: opts.milestone_id ?? null,
      slice_id: opts.slice_id ?? null,
      task_id: opts.task_id ?? null,
      full_content: contentToPersist,
    });

    // Write the file to disk (only if we're not preserving a richer existing file)
    if (!skipDiskWrite) {
      try {
        await saveFile(fullPath, contentToPersist);
      } catch (diskErr) {
        logWarning('projection', 'artifact projection write failed; DB artifact remains committed', { fn: 'saveArtifactToDbByScope', path: opts.path, error: String((diskErr as Error).message) });
      }
    }
    // Invalidate file-read caches so deriveState() sees the updated markdown.
    // Do NOT clear the artifacts table — we just wrote to it intentionally.
    invalidateStateCache();
    clearPathCache();
    clearParseCache();
  } catch (err) {
    logError('manifest', 'saveArtifactToDbByScope failed', { fn: 'saveArtifactToDbByScope', error: String((err as Error).message) });
    throw err;
  }
}

/**
 * Save an artifact to DB and write the corresponding markdown file to disk.
 * The path is relative to .gsd/ (e.g. "milestones/M001/slices/S06/tasks/T01-SUMMARY.md").
 * The full file path is computed as basePath + '.gsd/' + path.
 *
 * @deprecated Use saveArtifactToDbByScope instead, which routes through the
 * workspace contract for canonical path resolution.
 * TODO(C-future): remove this legacy wrapper once all callers are migrated.
 */
export async function saveArtifactToDb(
  opts: SaveArtifactOpts,
  basePath: string,
): Promise<void> {
  const workspace = createWorkspace(basePath);
  const milestoneId = opts.milestone_id;
  if (milestoneId) {
    return saveArtifactToDbByScope(scopeMilestone(workspace, milestoneId), opts);
  }
  return saveArtifactToDbForWorkspace(workspace, opts);
}
